### ISSUE TITLE
Images 

### ISSUE THREAD

**Issue by cyr3ne** [SedesGobhani/prj-rev-bwfs-dasmoto#1]
https://github.com/SedesGobhani/prj-rev-bwfs-dasmoto/blob/c266afc098b88fd724140301aa5383873d53a135/Dasmotos/index.html#L13

Images properly linked and viewable. 
 
In the future, you will learn how to host these picture files and resources locally within your project.
The benefit of that is, your project will always be online if the site hosting your images is down.

**Comment by SedesGobhani** [comment]
OK Thanks!
